[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "emuse"
version = "0.1.0"
description = "Report generator for the TRANA 16S rRNA taxonomic profiling pipeline"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
  "jinja2",
  "pandas",
  "pyyaml",
  "pysam",
]

[project.urls]
Homepage = "https://github.com/kclinmicro/TranaVy"

[project.scripts]
emuse = "emuse.make_report:main"

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
emuse = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
jinja2 = ">=3.1.6,<4"
pyyaml = ">=6.0.3,<7"
pandas = ">=3.0.2,<4"
pysam = ">=0.23.3,<0.24"
ipdb = ">=0.13.13,<0.14"
pytest = ">=9.0.3,<10"
minimap2 = ">=2.30,<3"

[tool.setuptools.packages.find]
include = ["emuse*"]

[tool.setuptools.package-data]
emuse = ["data/**/*"]

